### ISSUE TITLE
vncserver: couldn't find "uname" on your PATH

### ISSUE THREAD

**Issue by Pierrelemoine** [OSC/bc_desktop#10]
Hi,
I am trying to use bc desktop with ood, centos7.6, xfce and tigervnc.

When I request a session, it crashs and when I look at the output.log, I see:

    Setting VNC password...
    Starting VNC server...
    vncserver: couldn't find "uname" on your PATH.
    vncserver: couldn't find "uname" on your PATH.
    
It does the same with turbovnc.

I am unable to find a solution on the web and I don't want to modify vncserver check. 
Is that a known issue? Is there a way to fix it?

Thanks

**Comment by MorganRodgers** [comment]
@Pierrelemoine I suspect that you have something misconfigured which has broken the `$PATH` that is being used. If you are willing to edit the files to troubleshoot you could change the content of the file at `/var/www/ood/apps/sys/bc_desktop/template/script.sh.erb` to confirm what is available in the `$PATH` for the per-user-nginx that is attempting to launch the VNC server:

```bash
#!/usr/bin/env bash

# Change working directory to user's home directory
cd "${HOME}"

# Reset module environment (may require login shell for some HPC clusters)
module purge && module restore

echo "$PATH"

# Start up desktop
echo "Launching desktop '<%= context.desktop %>'..."
source "<%= session.staged_root.join("desktops", "#{context.desktop}.sh") %>"
echo "Desktop '<%= context.desktop %>' ended..."
```
You may also wish to check the content of the `/bin` directory as that is where `uname` should be installed on Centos 7.6 systems.

**Comment by Pierrelemoine** [comment]
@MorganRodgers : Where can I check the output of the script?
Uname is in /bin/ directory on the node

**Comment by MorganRodgers** [comment]
System installed BatchConnect applications write their output to `$HOME/ondemand/data/sys/dashboard/batch_connect/sys/$APP_NAME/output/$UUID/output.log`, where `$APP_NAME` in this case is `bc_desktop`.

**Comment by Pierrelemoine** [comment]
@MorganRodgers : I was looking at this log before but I can't see more things here.
If I put echo "$PATH" in  `/var/www/ood/apps/sys/bc_desktop/template/script.sh.erb`
I don't see anything in the logs.

I tried to modify:
- /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/gems/ood_core-0.5.0/lib/ood_core/batch_connect/templates/vnc.rb: 
- /var/www/ood/apps/sys/myjobs/vendor/bundle/ruby/gems/ood_core-0.3.0/lib/ood_core/batch_connect/templates/vnc.rb:

By adding:  export PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
But I don't see any positive result.
When I look at job_script_content.sh generate for a new job submission, I don't see the modifications I did in the vnc.rb files, , even after logged out and restart httpd? Do I miss something?

Finally, it looks like someone had similar issues but the developpers did not really give a solution here: https://listsprd.osu.edu/pipermail/ood-users/2018-July/000194.html

thanks

**Comment by MorganRodgers** [comment]
@Pierrelemoine if you have multiple copies of the dependency `ood_core` then you have either installed OOD a few times or attempted an upgrade. If you would like to experiment further with modifying `ood_core` then you should ensure that you are modifying the one that the application is using by checking the Gemfile.lock for a line like `ood_core ($VERSION_NUMBER)`.

Restarting the Apache daemon is unlikely to make a difference because with OOD it is the NGINX instances that perform actions as the authenticated OOD user. If you are able to see the OOD dashboard the easiest way to restart your NGINX process is to use the 'Restart Web Server' action underneath the Help menu. Alternatively if you are working on a test system you could also try ` /opt/ood/nginx_stage/sbin/nginx_stage nginx -u $USER -s reload`.

**Comment by Pierrelemoine** [comment]
@MorganRodgers : It's now ood_core version 0.7.1.
I modified the file `/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_core-0.7.1/lib/ood_core/batch_connect/templates/vnc.rb`
and I was able to see a modification.

Basically, my env at this point is completly broken, so I added this to make it work:

    export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    export HOME=/home/pierre

Then I am stuck again but later, it says:

    Setting VNC password...
    Error: no HOME environment variable
    Starting VNC server...
    
    Warning: skyintel01.cluster:1 is taken because of /tmp/.X1-lock
    Remove this file if there is no X server skyintel01.cluster:1
    Killing Xvnc process ID 170773
    Xvnc process ID 170773 already killed
    Xvnc did not appear to shut down cleanly. Removing /tmp/.X11-unix/X1
    Xvnc did not appear to shut down cleanly. Removing /tmp/.X1-lock
    
    Desktop 'TurboVNC: skyintel01.cluster:1 ()' started on display skyintel01.cluster:1
    
    Log file is vnc.log
    Successfully started VNC server on skyintel01.cluster:5901...
    Script starting...
    Starting websocket server...
    /home/pierre/ondemand/data/sys/dashboard/batch_connect/sys/bc_desktop/cluster/output/a417ec12-6127-4de3-92b4-01b005862289/script.sh: line 7: module: command not found
    Launching desktop 'xfce'...
    /var/spool/slurmd/job01482/slurm_script: line 145: /opt/websockify/run: No such file or directory
    Scanning VNC log file for user authentications...
    Generating connection YAML file...
    generating cookie with syscall
    generating cookie with syscall
    generating cookie with syscall
    generating cookie with syscall
    
    (xfce4-session:171304): xfce4-session-WARNING **: 17:52:24.473: xfsm_manager_load_session: Something wrong with /home/pierre/.cache/sessions/xfce4-session-skyintel01.cluster:1, Does it exist? Permissions issue?

I checked and /home/pierre/.cache/sessions/xfce4-session-skyintel01.cluster:1 does not exist.
I also don't have any file /opt/websockify/run on the head node

Do you know why the env is completly wiped out by the system and also why xfce4 fails?

thanks

**Comment by Pierrelemoine** [comment]
@MorganRodgers: I did some improvements and read the documentation again.
I added this to `/etc/ood/config/clusters.d/cluster.yml`

    batch_connect:
      basic:
        script_wrapper: |
          module purge
          %s
      vnc:
        script_wrapper: |
          module purge
    	  export HOME="/home/pierre"
          export PATH="/opt/TurboVNC/bin:$PATH"
          export WEBSOCKIFY_CMD="/usr/bin/websockify"
          %s

Now I am able to launch the session but I can't connect through the web interface, it says "failed to connect".
I try to connect from a ssh session directly on the machine and tigervnc viewer and it works.

So two questions remain:
- Why my environment is completly wiped out with interactive submission and with the job submission module as well?
- Why the vnc connection to the vncsession with the web interface fails?

Any idea?

Thanks.

**Comment by dantespe** [comment]
Any update on this issue? I'm having a similar issue to @Pierrelemoine where we get a "Failed to connect to server" noVNC error.

**Comment by MorganRodgers** [comment]
@Pierrelemoine and @dantespe: ensure that your `/etc/ood/config/ood_portal.yml` contains values for the keys `node_uri` and `rnode_uri`. In the same file ensure that the value for key `host_regex` can match the hostname(s) of the compute node(s) that is running the vnc server as detailed in [Enable Reverse Proxy](https://osc.github.io/ood-documentation/master/app-development/interactive/setup/enable-reverse-proxy.html?highlight=rnode#steps-to-enable-in-apache).

The other config to make note of is `/etc/ood/config/nginx_stage.yml` where you can specify custom environment variables using the keys `pun_custom_env` to declare custom environment variables, and `pun_custom_env_declarations` which exposes already set variables to the per user Nginx . An example is available on [Github](https://github.com/OSC/ondemand/blob/d85a3982d69746144d12bb808d2419b42ccc97a1/nginx_stage/share/nginx_stage_example.yml#L26-L43).

**Comment by ericfranz** [comment]
Note: unlike all other config files in OnDemand, changes to `/etc/ood/config/ood_portal.yml` are only applied after running the ood-portal-generator script that generates `/opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf`. The link Morgan shared above on enabling reverse proxy includes running a command like `sudo /opt/ood/ood-portal-generator/sbin/update_ood_portal` which will use the configuration file  `/etc/ood/config/ood_portal.yml` + default options as the context to render an Apache config template file to create a new version of `/opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf`.

**Comment by dantespe** [comment]
We figured it out. We had an incorrect regex (`host_regex`)

**Comment by ericfranz** [comment]
@dantespe glad you figured it out! Can you imagine anything that would have helped you more quickly/painlessly debug and identify this problem? We want to improve the installation experience so any feedback you have is very valuable.
