### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by ghost** [OSC/bc_desktop#7]
The "Install Desktops" link in the configuration section points to a 404 : https://osc.github.io/ood-documentation/master/install-desktops.html

![image](https://user-images.githubusercontent.com/7040493/45967438-0ae14780-bffc-11e8-8b10-a7d4f5ae230b.png)
![image](https://user-images.githubusercontent.com/7040493/45967445-0e74ce80-bffc-11e8-870d-4ad84e89b174.png)

**Comment by MorganRodgers** [comment]
Thanks for pointing that out @mancoast!

**Comment by ghost** [comment]
No problem!
